#! /bin/sh
### BEGIN INIT INFO
# Provides:          osmo-oohmi
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OpenBSC and OsmoSGSN HLR Management Interface
# Description:       Web Management interface for OpenBSC, OsmoSGSN, GGSN, Asterisk and LCR services.
### END INIT INFO
cd /etc/openbsc/
case "$1" in
	start)
		/usr/local/bin/pserve production.ini start ;;
	stop)
		/usr/local/bin/pserve production.ini stop ;;
	restart)
		/usr/local/bin/pserve production.ini restart ;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1 ;;
esac
exit 0
